_target_: src.datamodules.snow_dm.PairedSnowDataModule

train_dir: '/data1/wangding/datasets/CSD/Train/'
test_dir: '/data1/wangding/datasets/CSD/Test/'
subdirs: ['Snow', 'Gt', 'Mask']
train_val_split: 0.7
seed: 2020
batch_size: 16
num_workers: 8
pin_memory: True
