_target_: src.datamodules.snow_dm.PairedSnowDataModule

train_dir: '/data1/wangding/datasets/Snow100K/train/'
test_dir: '/data1/wangding/datasets/Snow100K/test/Snow100K-S/'
subdirs: ['synthetic', 'gt', 'mask']
train_val_split: 0.7
seed: 2020
batch_size: 16
num_workers: 4
pin_memory: True
